# -*- coding: utf-8 -*-
"""Value_Pitch_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1guBineJAHYhf_KqHrBIWEnJdiSYkia_4
"""

# !pip install BeautifulSoup4

import requests
from bs4 import BeautifulSoup

url = "https://main.sci.gov.in/case-status"
headers = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36"

r = requests.get(url, {'headers':headers})

c = r.content

c

soup = BeautifulSoup(c,"html.parser")

print(soup.prettify())

lst = soup.find("p",{"id":"cap"})

lst[0].find('font')

